// front/svelte/src/routes/todos/components/TodoList.svelte
<script lang="ts">
	import type { Todo } from '$lib/api/types';
	import TodoItem from './TodoItem.svelte';

	export let className: string = '';
	export let todos: Todo[];
</script>

<ul class="flex flex-col flex-grow gap-2 {className}">
	{#each todos as todo}
		{#key todo.id}
			<TodoItem {todo} />
		{/key}
	{/each}
</ul>

// front/remix/app/routes/todos/components/TodoList.tsx
import { FC, PropsWithChildren } from 'react'
import { Todo } from '~/types/todos'
import { TodoItem } from './Todo'

interface TodoListProps extends PropsWithChildren {
    className: string
    todos: Todo[]
    deleteTodo: (id: string) => void
    saveTodo: (id: string, text: string) => void
}

export const TodoList: FC<TodoListProps> = ({ todos, deleteTodo, saveTodo, className }) => {
    return (
        <ul className={`${className} flex flex-col flex-grow gap-2`}>
            {todos.map((todo) => (
                <TodoItem
                    todo={todo}
                    key={todo.id}
                    deleteTodo={deleteTodo}
                    saveTodo={saveTodo}
                />
            ))}
        </ul>
    )
}
