// front/remix/app/routes/posts.$page/components/PostsFooter/PostsFooter.tsx
import { FC, PropsWithChildren } from 'react'
import { Link, useParams } from '@remix-run/react'

interface PostsFooterProps extends PropsWithChildren {}

export const PostsFooter: FC<PostsFooterProps> = () => {
    const { page } = useParams()
    const prevPage = page ? +page - 1 : 1
    const nextPage = page ? +page + 1 : 2

    return (
        <footer className="fixed bottom-0 flex gap-3 items-center p-2 bg-indigo-800 text-indigo-200 rounded-t-lg left-1/2 -translate-x-1/2 ">
            {+page! > 1 && <Link className='p-2' to={`/posts/${prevPage}`}>{prevPage}</Link>}
            <Link className='p-2 text-amber-600' to={`/posts/${page}`}>{page}</Link>
            <Link className='p-2' to={`/posts/${nextPage}`}>{nextPage}</Link>
        </footer>
    )
}

// front/qwik/src/routes/posts/[page]/components/PostsFooter/PostsFooter.tsx
import { component$ } from "@builder.io/qwik"
import { Link, useLocation } from "@builder.io/qwik-city"

export default component$(() => {
    const page = useLocation().params.page
    const prevPage = page ? +page - 1 : 1
    const nextPage = page ? +page + 1 : 2

    return (
        <footer class="fixed bottom-0 flex gap-3 items-center p-2 bg-indigo-800 text-indigo-200 rounded-t-lg left-1/2 -translate-x-1/2 ">
            {+page! > 1 && <Link class='p-2' href={`/posts/${prevPage}`}>{prevPage}</Link>}
            <Link class='p-2 text-amber-600' href={`/posts/${page}`}>{page}</Link>
            <Link class='p-2' href={`/posts/${nextPage}`}>{nextPage}</Link>
        </footer>
    )
})
