// front/stencil/src/pages/Todos/components/TodoList/TodoList.tsx
import { Component, Prop, h, Event, EventEmitter } from '@stencil/core';
import { Todo } from '../../../../types/todos';
import '../TodoItem/TodoItem';

@Component({
  tag: 'todo-list',
  styleUrls: ['../../../../index.css'],
  shadow: true,
})
export class TodoList {
  @Prop()
  todos: Todo[] = [];

  @Event()
  deleteTodo: EventEmitter<string>;

  @Event()
  saveTodo: EventEmitter<{ id: string; text: string }>;

  private onDeleteTodoHandler(id: string) {
    this.deleteTodo.emit(id);
  }

  private onSaveHandler(payload: { id: string; text: string }) {
    this.saveTodo.emit(payload);
  }

  render() {
    return (
      <ul class="flex flex-col flex-grow gap-2">
        {this.todos.map(todo => (
          <todo-item
            todo={todo}
            key={todo.id}
            onDeleteTodo={event => {
              event.stopPropagation()
              this.onDeleteTodoHandler(event.detail);
            }}
            onSaveTodo={event => {
              event.stopPropagation()
              this.onSaveHandler(event.detail);
            }}
          ></todo-item>
        ))}
      </ul>
    );
  }
}

// front/angular/src/app/pages/todos/components/todo-list/todo-list.component.ts
import { Component, EventEmitter, HostBinding, Input, Output } from '@angular/core';
import { Todo } from '../../../../types/todos';
import { TodoItemComponent } from '../todo-item/todo-item.component';

@Component({
    selector: 'app-todo-list',
    standalone: true,
    imports: [TodoItemComponent],
    templateUrl: './todo-list.component.html',
})
export class TodoListComponent {
    @Input({ required: true }) todos: Todo[] = []
    @Input('class') className: string = ''

    @Output() deleteTodo = new EventEmitter<string>()
    @Output() saveTodo = new EventEmitter<Omit<Todo, 'timestamp'>>()

    onDeleteTodo(id: string) {
        this.deleteTodo.emit(id)
    }
    onSaveTodo(todo: Omit<Todo, 'timestamp'>) {
        this.saveTodo.emit(todo)
    }
}

<ul [class]="'flex flex-col flex-grow gap-2 ' + className">
    @for (todo of todos; track todo.id) {
    <app-todo-item
        [todo]="todo"
        (deleteTodo)="onDeleteTodo($event)"
        (saveTodo)="onSaveTodo($event)"
    ></app-todo-item>
    }
</ul>
