// front/lit/src/pages/app.ts
import { LitElement, html } from 'lit'
import { customElement } from 'lit/decorators.js'
import { TailwindElement } from '../utils/tailwindMixin'
import '../components/UI/Header/Header'
import '../components/UI/Cart/Cart'

@customElement('lit-app')
export class App extends TailwindElement() {
    render() {
        return html`
            <div class="flex flex-col min-h-screen">
                <header-component></header-component>
                <cart-component></cart-component>
                <main class="flex flex-col flex-1 p-4 w-full max-w-5xl mx-auto box-border">
                    <slot></slot>
                </main>
            </div>
        `
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'lit-app': App
    }
}

// front/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/UI/header/header.component';
import { CartComponent } from './components/UI/cart/cart.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent, CartComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
}

<div class="flex flex-col min-h-screen">
    <app-header></app-header>
    <app-cart></app-cart>
    <main class="flex flex-col flex-1 p-4 w-full max-w-5xl mx-auto box-border">
        <router-outlet />
    </main>
</div>
