// front/stencil/src/pages/app.tsx
import { Component, Prop, h } from '@stencil/core';
import '../components/UI/Header/Header'
import '../components/UI/Cart/Cart'

@Component({
  tag: 'stencil-app',
  styleUrl: '../index.css',
  shadow: true,
})
export class App {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string = 'none';

  /**
   * The last name
   */
  @Prop() last: string;

  // private getText(): string {
  //   return `${this.first} ${this.middle} ${this.last}`;
  // }

  render() {
    return (
      <div class="flex flex-col min-h-screen">
        <header-component></header-component>
        <cart-component></cart-component>
        <main class="flex flex-col flex-1 p-4 w-full max-w-5xl mx-auto box-border">
          <slot></slot>
        </main>
      </div>
    );
  }
}

// front/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/UI/header/header.component';
import { CartComponent } from './components/UI/cart/cart.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent, CartComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
}

<div class="flex flex-col min-h-screen">
    <app-header></app-header>
    <app-cart></app-cart>
    <main class="flex flex-col flex-1 p-4 w-full max-w-5xl mx-auto box-border">
        <router-outlet />
    </main>
</div>
