// front/next/app/todos/components/TodoForm.tsx
"use client";

import { useState, type FC, type PropsWithChildren } from "react";
import { Input } from "@/components/UI/Input/Input";
import { Todo } from "@/types/todos";
import { useFormState, useFormStatus } from "react-dom";

interface TodoFormProps extends PropsWithChildren {
    readonly addTodo: (formData: FormData) => Promise<Todo[]>;
}

const TodoForm: FC<TodoFormProps> = ({ addTodo }) => {
    const [todoText, setTodoText] = useState("");
    // const [state, formAction] = useFormState(someAction, initialState);

    const addTodoHandler = (formData: FormData) => {
        const timestamp = Date.now();
        formData.append("timestamp", String(timestamp));
        addTodo(formData);
        setTodoText('')
    };

    return (
        <form className="flex justify-between gap-3" action={addTodoHandler}>
            <Input value={todoText} onChange={setTodoText} name="text" />
            <SubmitButton />
        </form>
    );
};

function SubmitButton() {
    const { pending } = useFormStatus();

    return (
        <button
            disabled={pending}
            type="submit"
            className="inline-flex justify-center items-center p-2 text-sm font-medium text-center text-white bg-green-500 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"
        >
            {pending ? "Loading" : "Add"}
        </button>
    );
}

export default TodoForm;

// front/angular/src/app/pages/todos/components/todo-form/todo-form.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms'; //FormsModule for app-input with [(value)]="newTodo"
import { InputComponent } from '../../../../components/Input/input.component';
import { OtherInputComponent } from '../../../../components/OtherInput/OtherInput.component';
import { NgClass } from '@angular/common';

@Component({
    selector: 'app-todo-form',
    standalone: true,
    imports: [InputComponent, ReactiveFormsModule, OtherInputComponent, NgClass],
    templateUrl: './todo-form.component.html',
})

export class TodoFormComponent {
    todoForm = new FormGroup({
        text: new FormControl('', Validators.required),
    });

    @Output() addTodo = new EventEmitter<{ text: string }>()

    async onSubmit(e: SubmitEvent) {
        //@ts-expect-error
        this.addTodo.emit(this.todoForm.value);
        this.todoForm.reset()
    }
}

<form
    [formGroup]="todoForm"
    (ngSubmit)="onSubmit($event)"
    class="flex justify-between gap-3 w-full"
>
    <app-other-input
        class="w-full"
        formControlName="text"
    >
    </app-other-input>
    <button
        [disabled]="!todoForm.valid"
        type="submit"
        [ngClass]="{'inline-flex justify-center items-center p-2 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none': true, 'bg-green-500 hover:bg-green-800 focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800': todoForm.valid, 'bg-green-300 hover:bg-green-500 focus:ring-green-100 dark:bg-green-300 dark:hover:bg-green-400 dark:focus:ring-green-500': !todoForm.valid}"
    >
        Add
    </button>
</form>
