// front/solid/src/App.tsx
import { ErrorBoundary, type Component, type ParentProps } from 'solid-js'
import { Header } from './components/Header/Header'
import { Cart } from './components/Cart/Cart'

const App: Component<ParentProps> = (props) => {
    return (
        <>
            <Header />
            <Cart />
            <ErrorBoundary
                fallback={(err) => (
                    <p class="mt-4 text-center text-lg font-bold w-full">Whoopsie. Something went wrong</p>
                )}
            >
                <main class="flex flex-col flex-1 p-4 w-full max-w-5xl mx-auto box-border">{props.children}</main>
            </ErrorBoundary>
        </>
    )
}

export default App

// front/lit/src/pages/app.ts
import { LitElement, html } from 'lit'
import { customElement } from 'lit/decorators.js'
import { TailwindElement } from '../utils/tailwindMixin'
import '../components/UI/Header/Header'
import '../components/UI/Cart/Cart'

@customElement('lit-app')
export class App extends TailwindElement() {
    render() {
        return html`
            <div class="flex flex-col min-h-screen">
                <header-component></header-component>
                <cart-component></cart-component>
                <main class="flex flex-col flex-1 p-4 w-full max-w-5xl mx-auto box-border">
                    <slot></slot>
                </main>
            </div>
        `
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'lit-app': App
    }
}
