// front/solid/src/components/Spinner/Spinner.tsx
import { Component, ParentProps, mergeProps } from 'solid-js'
import classes from './Spinner.module.css'

interface SpinnerProps extends ParentProps {
    readonly size?: string
    readonly color?: string
    readonly width?: string
}

export const Spinner: Component<SpinnerProps> = (_props) => {
    const props = mergeProps({ size: '10px', color: '#fff', width: '6px' }, _props)
    const containerSize = parseInt(props.size, 10) + 16 + 'px'
    return (
        <div
            class={classes['lds-dual-ring']}
            style={{
                '--size': props.size,
                '--color': props.color,
                '--containerSize': containerSize,
                '--width': props.width,
            }}
        />
    )
}

// front/qwik/src/components/Spinner/Spinner.tsx
import { component$ } from "@builder.io/qwik";
import classes from "./Spinner.module.css";

interface SpinnerProps {
    readonly size?: string;
    readonly color?: string;
    readonly width?: string;
}

export default component$(
    ({ size = "10px", color = "#fff", width = "6px" }: SpinnerProps) => {
        const containerSize = parseInt(size, 10) + 16 + "px";
        return (
            <div
                class={classes["lds-dual-ring"]}
                style={{
                    "--size": size,
                    "--color": color,
                    "--containerSize": containerSize,
                    "--width": width,
                }}
            />
        );
    }
);
