// front/qwik/src/routes/post/[id]/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";
import { getPostById } from "~/api/posts";
import ItemCard from "~/routes/posts/[page]/components/ItemCard/ItemCard";

export const usePost = routeLoader$(async (requestEvent) => {
    const page = requestEvent.url.pathname;
    const id = page.split("/").at(-2);

    const response = await getPostById(id!);
    return response;
});

export default component$(() => {
    const post = usePost()

    return (
        <>
            <div class="flex-grow flex justify-center items-center">
                <div class="flex justify-center item h-full">
                    <ItemCard post={post.value} showFooter={false} />
                </div>
            </div>
        </>
    );
});

export const head: DocumentHead = {
    title: "Post",
    meta: [
        {
            name: "description",
            content: "Some description",
        },
    ],
};

// front/next/app/post/[id]/page.tsx
import { getPostById } from "@/api/posts";
import { ItemCard } from "@/app/posts/[id]/components/ItemCard/ItemCard";
import { Post } from "@/types/posts";
import { PropsWithChildren } from "react";

interface PostProps extends PropsWithChildren {
    params: {
        id: string;
    };
}

export default async function Post({ params }: PostProps) {
    const { id } = params;
    const post = await getPostById(id as string);

    ///@ts-expect-error
    if (post.errors) {
        return <p>Oops. Some error</p>;
    }

    return (
        <>
            <div className="flex-grow flex justify-center items-center">
                <div className="flex justify-center item h-full">
                    <ItemCard post={post as Post} showFooter={false} />
                </div>
            </div>
        </>
    );
}
