// front/qwik/src/routes/todos/components/TodoList.tsx
import type { Todo as ITodo } from "~/types/todos";
import { component$ } from "@builder.io/qwik";
import Todo from "./Todo";
import type { ActionStore } from "@builder.io/qwik-city";
import { Action } from "@builder.io/qwik-city";

interface TodoListProps {
    class: string;
    todos: ITodo[];
    deleteTodo: ActionStore<{}, Record<string, unknown>, true>
    editTodo: ActionStore<{}, Record<string, unknown>, true>
}

export default component$((props: TodoListProps) => {
    return (
        <ul class={`${props.class} flex flex-col flex-grow gap-2`}>
            {props.todos.map((todo) => (
                <Todo
                    todo={todo}
                    key={todo.id}
                    deleteTodo={props.deleteTodo}
                    editTodo={props.editTodo}
                />
            ))}
        </ul>
    );
});

// front/next/app/todos/components/TodoList.tsx
import { FC, PropsWithChildren } from "react";
import { TodoItem } from "./Todo";
import { Todo } from "@/types/todos";

interface TodoListProps extends PropsWithChildren {
    className: string;
    todos: Todo[];
    deleteTodo: (formData: FormData) => Promise<Todo[]>;
    editTodo: (formData: FormData) => Promise<Todo[]>;
}

export const TodoList: FC<TodoListProps> = ({
    todos,
    deleteTodo,
    editTodo,
    className,
}) => {
    return (
        <ul className={`${className} flex flex-col flex-grow gap-2`}>
            {todos.map((todo) => (
                <TodoItem
                    todo={todo}
                    key={todo.id}
                    deleteTodo={deleteTodo}
                    editTodo={editTodo}
                />
            ))}
        </ul>
    );
};
