// front/solid/src/pages/Posts/Posts.tsx
import { Component, For, Show, createResource } from 'solid-js'
import { Post } from '../../types/posts'
import { PostsFooter } from './components/PostsFooter/PostsFooter'
import { ItemCard } from '../../components/ItemCard/ItemCard'
import { getPostsByPage } from '../../api/posts'
import { useParams } from '@solidjs/router'
import { Spinner } from '../../components/Spinner/Spinner'

const Posts: Component = () => {
    const params = useParams()
    const [posts] = createResource(() => ({ page: params.page }), getPostsByPage)

    return (
        <>
            <Show
                when={!posts.loading}
                fallback={
                    <div class="w-full flex justify-center m-auto mt-5">
                        <Spinner
                            size="130px"
                            color="#F87171"
                            width="7px"
                        />
                    </div>
                }
            >
                <div class="flex-grow">
                    <div class="grid gap-4 grid-cols-1 sm:grid-cols-2">
                        <For each={posts() as Post[]}>
                            {(post) => (
                                <div class="flex justify-center item h-full">
                                    <ItemCard post={post} />
                                </div>
                            )}
                        </For>
                    </div>
                </div>
            </Show>

            <PostsFooter />
        </>
    )
}

export default Posts

// front/angular/src/app/pages/posts/posts.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { PostService } from '../../api/post/post.service';
import { Post } from '../../types/posts';
import { PostItemComponent } from '../post/components/post-item/post-item.component';
import { SpinnerComponent } from '../../components/UI/spinner/spinner.component';
import { PostsFooterComponent } from './components/posts-footer/posts-footer.component';

@Component({
    selector: 'app-posts',
    standalone: true,
    imports: [PostItemComponent, SpinnerComponent, PostsFooterComponent],
    templateUrl: './posts.component.html',
})
export class PostsComponent implements OnInit {
    page: string;
    postService: PostService = inject(PostService)
    loading = false
    error: string | null = null
    posts: null | Post[] = null

    constructor(private activateRoute: ActivatedRoute) {
        this.page = activateRoute.snapshot.params['page'];
        activateRoute.params.subscribe(routeParams => {
            this.page = routeParams['page']
            if (this.page) {
                this.getPosts(this.page)
            }
        })
    }

    async ngOnInit(): Promise<void> {
        if (this.page) {
            await this.getPosts(this.page)
        }
    }

    private async getPosts(page: string) {
        try {
            this.loading = true
            const post = await this.postService.getPostsByPage(this.page)
            ///@ts-expect-error
            if (!post.errors) {
                this.posts = (post as Post[])
            } else {
                ///@ts-expect-error
                this.error = post.errors[0]
            }
        } catch (error) {
            this.error = 'Something went wrong'
            console.log(error)
        } finally {
            this.loading = false
        }
    }
}

<div class="flex-grow">
    @if (loading) {
    <div class="flex justify-center item h-full w-full flex-grow">
        <app-spinner size="120px"></app-spinner>
    </div>
    }
    @else if (posts) {
    <div class="grid gap-4 grid-cols-1 sm:grid-cols-2">
        @for (post of posts; track post.id) {
        <div class="flex justify-center item h-full">
            <app-post-item [post]="post" />
        </div>
        }
    </div>
    } @else {
    <p>Whoopsie. No post :(</p>
    @if (error) {
    <p>Reason: {{error}}</p>
    }
    }

</div>
<app-posts-footer></app-posts-footer>
