// front/next/app/todos/components/TodoList.tsx
import { FC, PropsWithChildren } from "react";
import { TodoItem } from "./Todo";
import { Todo } from "@/types/todos";

interface TodoListProps extends PropsWithChildren {
    className: string;
    todos: Todo[];
    deleteTodo: (formData: FormData) => Promise<Todo[]>;
    editTodo: (formData: FormData) => Promise<Todo[]>;
}

export const TodoList: FC<TodoListProps> = ({
    todos,
    deleteTodo,
    editTodo,
    className,
}) => {
    return (
        <ul className={`${className} flex flex-col flex-grow gap-2`}>
            {todos.map((todo) => (
                <TodoItem
                    todo={todo}
                    key={todo.id}
                    deleteTodo={deleteTodo}
                    editTodo={editTodo}
                />
            ))}
        </ul>
    );
};

// front/solid/src/pages/Todos/components/TodoList.tsx
import { Component, ParentProps, For } from 'solid-js'
import { Todo } from '../../../types/todos'
import { TodoItem } from './TodoItem'

interface TodoListProps extends ParentProps {
    class: string
    todos: Todo[]
    deleteTodo: (id: string) => void
    editTodo: (id: string, text: string) => void
}

export const TodoList: Component<TodoListProps> = (props) => {
    return (
        <ul class={`${props.class} flex flex-col flex-grow gap-2`}>
            <For each={props.todos}>
                {(todo) => (
                    <TodoItem
                        todo={todo}
                        deleteTodo={props.deleteTodo}
                        editTodo={props.editTodo}
                    />
                )}
            </For>
        </ul>
    )
}
