// front/remix/app/routes/todos/components/TodoList.tsx
import { FC, PropsWithChildren } from 'react'
import { Todo } from '~/types/todos'
import { TodoItem } from './Todo'

interface TodoListProps extends PropsWithChildren {
    className: string
    todos: Todo[]
    deleteTodo: (id: string) => void
    saveTodo: (id: string, text: string) => void
}

export const TodoList: FC<TodoListProps> = ({ todos, deleteTodo, saveTodo, className }) => {
    return (
        <ul className={`${className} flex flex-col flex-grow gap-2`}>
            {todos.map((todo) => (
                <TodoItem
                    todo={todo}
                    key={todo.id}
                    deleteTodo={deleteTodo}
                    saveTodo={saveTodo}
                />
            ))}
        </ul>
    )
}

// front/solid/src/pages/Todos/components/TodoList.tsx
import { Component, ParentProps, For } from 'solid-js'
import { Todo } from '../../../types/todos'
import { TodoItem } from './TodoItem'

interface TodoListProps extends ParentProps {
    class: string
    todos: Todo[]
    deleteTodo: (id: string) => void
    editTodo: (id: string, text: string) => void
}

export const TodoList: Component<TodoListProps> = (props) => {
    return (
        <ul class={`${props.class} flex flex-col flex-grow gap-2`}>
            <For each={props.todos}>
                {(todo) => (
                    <TodoItem
                        todo={todo}
                        deleteTodo={props.deleteTodo}
                        editTodo={props.editTodo}
                    />
                )}
            </For>
        </ul>
    )
}
