// front/qwik/src/components/Header/Header.tsx
import { component$ } from "@builder.io/qwik";
import classes from "./Header.module.css";
import { Link, useLocation } from "@builder.io/qwik-city";

export default component$(() => {
    const links = [
        { name: "Home", link: "/" },
        { name: "Posts", link: "/posts/1" },
        { name: "About", link: "/about" },
        { name: "Todos", link: "/todos" },
    ] as const;

    const url = useLocation().url;
    
    return (
        <header class={classes.header}>
            <nav class="w-full flex justify-center">
                <svg
                    viewBox="0 0 2 3"
                    class={classes.svg + " text-indigo-800"}
                    aria-hidden="true"
                >
                    <path
                        class="fill-current"
                        d="M0,0 L1,2 C1.5,3 1.5,3 2,3 L2,0 Z"
                    />
                </svg>
                <ul class="bg-indigo-800 flex justify-center items-center [&>li]:relative [&>li]:h-full">
                    {links.map((link) => (
                        <li key={link.name}>
                            <Link
                                class={`${classes.link} ${checkRouteMatch(link.link, url.pathname) ? "!text-amber-600" : ""}`}
                                href={link.link}
                            >
                                {link.name}
                            </Link>
                        </li>
                    ))}
                </ul>
                <svg
                    viewBox="0 0 2 3"
                    class={classes.svg + " text-indigo-800"}
                    aria-hidden="true"
                >
                    <path
                        class="fill-current"
                        d="M0,0 L0,3 C0.5,3 0.5,3 1,2 L2,0 Z"
                    />
                </svg>
            </nav>
        </header>
    );
});

function checkRouteMatch(link: string, currentRoute: string) {
    const regexp = /^\/([^/]+\/[^/]+)(\/.*)?$/;
    let routeWithoutParams = currentRoute.replace(regexp, "");
    const linkWithoutParams = link.replace(regexp, "");
    if (routeWithoutParams.length > 1 && routeWithoutParams.at(-1) === "/") {
        routeWithoutParams = routeWithoutParams.substring(
            0,
            routeWithoutParams.length - 1
        );
    }
    return routeWithoutParams === linkWithoutParams;
}

// front/stencil/src/components/UI/Header/Header.tsx
import { Component, State, h } from '@stencil/core';

@Component({
  tag: 'header-component',
  styleUrl: 'Header.css',
  shadow: true,
})
export class Header {
  private links = [
    { name: 'Home', link: '/' },
    { name: 'Posts', link: '/posts/1' },
    { name: 'About', link: '/about' },
    { name: 'Todos', link: '/todos' },
  ] as const;

  @State()
  private currentUrl = window.location.pathname;

  private _setCurrentLocation = () => {
    this.currentUrl = window.location.pathname;
  };

  connectedCallback() {
    window.addEventListener('popstate', this._setCurrentLocation);
  }

  disconnectedCallback() {
    window.removeEventListener('popstate', this._setCurrentLocation);
  }

  render() {
    return (
      <header class="header">
        <nav class="w-full flex justify-center">
          <svg viewBox="0 0 2 3" class="svg text-indigo-800" aria-hidden="true">
            <path class="fill-current" d="M0,0 L1,2 C1.5,3 1.5,3 2,3 L2,0 Z" />
          </svg>
          <ul class="bg-indigo-800 flex justify-center items-center [&>li]:relative [&>li]:h-full">
            {this.links.map(link => (
              <li key={link.link}>
                <a href={link.link} class={`link ${checkRouteMatch(link.link, this.currentUrl) ? 'text-amber-600' : 'text-slate-400'}`}>
                  {link.name}
                </a>
              </li>
            ))}
          </ul>
          <svg viewBox="0 0 2 3" class="svg text-indigo-800" aria-hidden="true">
            <path class="fill-current" d="M0,0 L0,3 C0.5,3 0.5,3 1,2 L2,0 Z" />
          </svg>
        </nav>
      </header>
    );
  }
}

function checkRouteMatch(link: string, currentRoute: string) {
  const regexp = /^\/([^/]+\/[^/]+)(\/.*)?$/;
  const routeWithoutParams = currentRoute.replace(regexp, '');
  const linkWithoutParams = link.replace(regexp, '');
  return routeWithoutParams === linkWithoutParams;
}
