// front/svelte/src/routes/todos/+page.svelte
<script lang="ts">
	import TodoForm from './components/TodoForm.svelte';
	import TodoList from './components/TodoList.svelte';

	export let data;
	$: todos = data.todos;
</script>

<svelte:head>
	<title>Todos</title>
	<meta name="description" content="Todo" />
</svelte:head>

<div class="w-1/2 mt-3 mx-auto">
	<TodoForm />
	<TodoList {todos} className="w-full mt-3" />
</div>

// front/next/app/todos/page.tsx
import { addTodo, getTodos, deleteTodo, editTodo } from "@/api/todos";
import { TodoList } from "./components/TodoList";
import TodoForm from "./components/TodoForm";

export default async function Todos() {
    const todos = await getTodos();

    return (
        <div className="w-1/2 mt-3 mx-auto">
            <TodoForm addTodo={addTodo} />
            <TodoList
                className="mt-3"
                todos={todos}
                deleteTodo={deleteTodo}
                editTodo={editTodo}
            />
        </div>
    );
}
