// front/solid/src/components/Spinner/FullScreenSpinner.tsx
import { Component, ParentProps, mergeProps } from 'solid-js'
import { Spinner } from './Spinner'

interface FullScreenSpinnerProps extends ParentProps {
    readonly color?: string
}

const FullScreenSpinner: Component<FullScreenSpinnerProps> = (_props) => {
    const props = mergeProps({ color: '#F87171' }, _props)
    return (
        <div class="absolute inset-0 flex justify-center items-center">
            <Spinner
                size="130px"
                color={props.color}
                width="7px"
            />
        </div>
    )
}
export default FullScreenSpinner

// front/next/components/UI/Spinner/FullScreenSpinner.tsx
import type { FC, PropsWithChildren } from "react";
import { Spinner } from "./Spinner";

interface FullScreenSpinnerProps extends PropsWithChildren {
    readonly color?: string;
}

const FullScreenSpinner: FC<FullScreenSpinnerProps> = ({
    color = "#F87171",
}) => {
    return (
        <div className="absolute inset-0 flex justify-center items-center">
            <Spinner size="130px" color={color} width="7px" />
        </div>
    );
};
export default FullScreenSpinner;
