// front/remix/app/components/UI/Cart/Cart.tsx
import { FC, PropsWithChildren } from 'react'
import { useCartStore } from '~/store/store'

interface CartProps extends PropsWithChildren {}

export const Cart: FC<CartProps> = () => {
    const { computed } = useCartStore((state) => state)

    return (
        <summary className="fixed top-0 right-0 flex gap-3 items-center p-2 bg-teal-800 text-teal-200 rounded-b-lg mr-4">
            <div>items: {computed.totalItems}</div>
            <div>total: {computed.totalPrice}</div>
        </summary>
    )
}

// front/stencil/src/components/UI/Cart/Cart.tsx
import { Component, h } from '@stencil/core';
import { totalItems, totalPrice } from '../../../store/store';

@Component({
  tag: 'cart-component',
  styleUrl: '../../../index.css',
  shadow: true,
})
export class About {
  render() {
    return (
      <summary class="fixed top-0 right-0 flex gap-3 items-center p-2 bg-teal-800 text-teal-200 rounded-b-lg mr-4">
        <div>items: {totalItems()}</div>
        <div>total: {totalPrice()}</div>
      </summary>
    );
  }
}
