// front/solid/src/pages/Todos/Todos.tsx
import { type Component, createSignal, createResource, Show, createEffect, JSX } from 'solid-js'
import { Input } from '../../components/Input/Input'
import { action, useAction, useSubmission, revalidate } from '@solidjs/router'
import { addTodo, deleteTodo, editTodo, getTodos } from '../../api/todos'
import { TodoList } from './components/TodoList'
import { Spinner } from '../../components/Spinner/Spinner'
import { Todo } from '../../types/todos'

const deleteTodoAction = action(deleteTodo)
const editTodoAction = action(editTodo)

const Todos: Component = () => {
    const addTodoAction = action(async (formData: FormData) => {
        const todo = await addTodo({ text: Object.fromEntries(formData).todoText as string, timestamp: Date.now() })
        formRef?.reset()
        return todo
    })

    const [todos, { refetch, mutate }] = createResource(getTodos)
    const myDeleteTodo = useAction(deleteTodoAction)
    const myEditTodo = useAction(editTodoAction)
    const echoingAddTodo = useSubmission(addTodoAction)

    const pushTodo = (todo: Todo) => {
        mutate([...todos()!, todo])
    }
    createEffect((prev) => {
        if (echoingAddTodo.result && echoingAddTodo.result !== prev) {
            pushTodo(echoingAddTodo.result)
        }
        return echoingAddTodo.result
    })

    const [todoText, setTodoText] = createSignal('')
    
    const onDeleteTodo = async (id: string) => {
        await myDeleteTodo(id)
        mutate(todos()?.filter((todo) => todo.id !== id))
        // refetch()
    }

    const editTodo = async (id: string, text: string) => {
        await myEditTodo({ id, text })
        // refetch()
    }

    let formRef: HTMLFormElement | undefined

    return (
        <div class="w-1/2 mt-3 mx-auto">
            <form
                class="flex justify-between gap-3"
                method="post"
                action={addTodoAction}
                ref={formRef}
            >
                <Input
                    value={todoText()}
                    onChange={setTodoText}
                    name="todoText"
                />
                <button
                    type="submit"
                    class="inline-flex justify-center items-center p-2 text-sm font-medium text-center text-white bg-green-500 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"
                >
                    Add
                </button>
            </form>

            <Show
                when={!todos.loading}
                fallback={
                    <div class="w-full flex justify-center m-auto mt-5">
                        <Spinner
                            size="130px"
                            color="#F87171"
                            width="7px"
                        />
                    </div>
                }
            >
                <TodoList
                    class="mt-3"
                    todos={todos()!}
                    deleteTodo={onDeleteTodo}
                    editTodo={editTodo}
                />
            </Show>
        </div>
    )
}

export default Todos

// front/lit/src/pages/Todos/Todos.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import '../../components/UI/Input/Input'
import { Task } from '@lit/task'
import { TailwindElement } from '../../utils/tailwindMixin'
import styles from './Todos.css?inline'
import { addTodo, deleteTodo, editTodo, getTodos } from '../../api/todos'
import { Todo } from '../../types/todos'
import './components/TodoList'
import '../../components/UI/Spinner/Spinner'

@customElement('todos-page')
export class Todos extends TailwindElement(styles) {
    @property()
    todoText = ''

    @property({ type: Array })
    todos: Todo[] = []

    private _setTodoText(event: CustomEvent<{ text: string }>) {
        this.todoText = event.detail.text
    }

    private async _onAddTodo() {
        await addTodo({ text: this.todoText, timestamp: Date.now() })
        this.todoText = ''
        this._todosTask.run()
    }

    private async _onDeleteTodo(id: string) {
        await deleteTodo(id)
        this._todosTask.run()
    }

    private async _editTodo(payload: { id: string; text: string }) {
        await editTodo(payload)
        this._todosTask.run()
    }

    private _todosTask = new Task(this, {
        task: async ([currentPage]) => {
            const response = await getTodos()
            if (response.errors) {
                throw new Error(response.errors[0])
            }
            this.todos = response
            return this.todos
        },
        args: () => [],
    })

    connectedCallback() {
        super.connectedCallback()
        this._todosTask.run()
    }

    render() {
        return html`
            <div class="w-1/2 mt-3 mx-auto">
                <form
                    class="flex justify-between gap-3 w-full"
                    method="post"
                    @submit=${(event: SubmitEvent) => {
                        event.preventDefault()
                        this._onAddTodo()
                    }}
                >
                    <input-component
                        .value="${this.todoText}"
                        @changeValue="${this._setTodoText}"
                    ></input-component>
                    <button
                        ?disabled="${!this.todoText}"
                        type="submit"
                        class=${`inline-flex justify-center items-center p-2 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none ${
                            !this.todoText
                                ? 'bg-green-300 hover:bg-green-500 focus:ring-green-100 dark:bg-green-300 dark:hover:bg-green-400 dark:focus:ring-green-500'
                                : 'bg-green-500 hover:bg-green-800 focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800'
                        }`}
                    >
                        Add
                    </button>
                </form>

                ${this._todosTask.render({
                    complete: (value) =>
                        html`<todo-list
                            .todos="${this.todos}"
                            @onDeleteTodo="${(event: CustomEvent<{ id: string }>) => {
                                this._onDeleteTodo(event.detail.id)
                            }}"
                            @onSaveTodo="${(event: CustomEvent<{ id: string; text: string }>) => {
                                this._editTodo(event.detail)
                            }}"
                        ></todo-list>`,
                    pending: () => html`
                        <div class="absolute inset-0 flex justify-center items-center">
                            <spinner-component></spinner-component>
                        </div>
                    `,
                })}
            </div>
        `
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'todos-page': Todos
    }
}

// <todo-list
// todos="{this.todos}"
// onDeleteTodo="{event"
// =""
// >
// { this._onDeleteTodo(event.detail); }} onSaveTodo={event => { this._editTodo(event.detail); }}
// ></todo-list
// >
